# Generated by Django 4.0.4 on 2022-05-04 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NONapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='author',
            new_name='user',
        ),
    ]
